function hdfwarn(status)
%Use the last error generated by the HDF library as a warning.

%   Copyright 1984-2010 The MathWorks, Inc.
%   $Revision: 1.1.6.6 $  $Date: 2011/05/17 02:27:41 $

if status==-1
  error_code = hdfhe('value',1);
  if strncmpi(hdfhe('string',error_code),'no error',8)
    warning(message('MATLAB:imagesci:hdfwarn:generic'));
  else
    warning(message('MATLAB:imagesci:hdfwarn:libraryError', hdfhe( 'string', error_code )));
  end
end
