function [BayesObject] = hyperPdeploy(optimVars,X,Y,vX,vY,exeEnvironment,maxE,toSlow,numClasses)
    

    ObjFcn = @(hyperParameters,trainX,trainY,valX,valY)makeObjFcn(hyperParameters,trainX,trainY,valX,valY,toSlow,'None',maxE,exeEnvironment{1},numClasses);
    
    
    BayesObject = bayesopt(@(OPS)ObjFcn(OPS,X,Y,vX,vY),...
        optimVars,...
        'MaxObj',90,...
        'MaxTime',2*60*60,...
        'IsObjectiveDeterministic',false,...
        'UseParallel',exeEnvironment{2});
end